--- 
application: 
  temp_folder: tmp_output_13.3.2
  storage: ../storage/dev-ecare-13.3.2/clearcase_output
  polling_time: 120
clearcase: 
  view: ecare_ecare_git_13.3.2_ux
  output: clearcase_output
  branch: dev-ecare-13.3.2
  configspec: develop_ecare_13.3.2_SP2_ux.txt
  modified_map: maps/clearcase_export.map
git: 
  output_folder: extracted
  branch: dev-ecare-13.3.2
  bare_repo: ../../repositories/ecare_dev.git
  modified_files_map: maps/modified_13.3.2.map
  tag: dev-ecare-13.3.2_128
  repo_name: ecare_dev.git
  stable_repo: ../../repositories/ecare_stable.git
  deleted_files_map: maps/deleted_13.3.2.map
  stable_repo_name: ecare_stable.git
  added_files_map: maps/added_13.3.2.map
